export const DESIGN_ITEMS = [
  "Client: Survey Plan received",
  "Site Inspection",
  "Concept plan",
  "Ground Plan - Options - 1, Options-2, Options-3 (optional)",
  "Client: Approval of Design and Material to be used",
  "Elevation Design - Option- 1, Option-2 and Option-3 (optional)",
  "Client: Approval of Master plan Design",
  "Section Drawings",
  "MEP Proposal - Structural Drawing, MEP Designs Follow ups after we approve",
  "Good For Construction Drawings are sent",
  "Flooring Plans",
  "Idol Designs for both Utsava and Main Idols",
  "Door Frames",
  "Door Shutters",
  "Dwajasthambham & Dwajasthambham Kavacham",
  "Kalasam"
];

export const OBSERVATION_ITEMS = [
  "Electrical provision in the Temple",
  "Plumbing provision in the Temple",
  "AC Points Provision in the Temple"
];

export const STONE_CONSTRUCTION_ITEMS = [
  "Client: Survey Plan received",
  "Temple Marking",
  "Senku sthapana",
  "Client: Civil work - Foundation, plinth beam and columns",
  "Garbhalaya - 4 Steps by laying stones",
  "Mandapam Upapeetam",
  "Mandapam Pillars",
  "Client: Civil work Garbhalaya and Mandapam - Slab",
  "Sikaram - 4 stages including stone idols on Gopuram",
  "Salaharam",
  "Dwajasthambham log purchase",
  "Client: Cement work - Dwajasthambham Peetam",
  "Dwajasthambham Brass Kavacham",
  "Raja Gopuram - 4 Stages Upto Prastharam",
  "Civil Work",
  "Sikaram - 4 stages",
  "Compound Wall"
];

export const CEMENT_CONSTRUCTION_ITEMS = [
  "Client: Survey of the Temple Area and surroundings",
  "Temple Marking",
  "Senku sthapana - Where a stone is put beneath the main Garbhalaya ground.",
  "Client: Civil work - Foundation, plinth beam and columns",
  "Garbhalaya - Brick work",
  "Plastering and Finishing",
  "Client: Civil work of RCC Columns and add Steps",
  "Client: Civil work Garbhalaya and Mandapam - Slab",
  "Sikaram Brick work",
  "Plastering and Finishing",
  "Salaharam Brick work",
  "Plastering and Finishing",
  "Cement Idols",
  "Dwajasthambham log purchase",
  "Client: Cement work - Dwajasthambham Peetam",
  "Dwajasthambham Brass Kavacham",
  "Door Frame - Making, Transportation, fixing",
  "Door Frame - QC for Making",
  "Door Frame - QC for Transportation",
  "Door Frame - QC for Fixing",
  "Door Shutters - Making, Transportation, Fixing, Polishing",
  "Door Shutters - QC for Making",
  "Door Shutters - QC for Transportation",
  "Door Shutters - QC for Fixing",
  "Door Shutters - QC for Polishing",
  "Dhwajatshambham - Making, Transportation, Fixing",
  "Dhwajatshambham - QC for Making",
  "Dhwajatshambham - QC for Transportation",
  "Dhwajatshambham - QC for Fixing",
  "Raja Gopuram - 4 Stages Upto Prastharam",
  "Client: Civil Work - Slab",
  "Sikaram - 4 stages",
  "Kalasam Designs",
  "Kalasam - QC for Making",
  "Kalasam - QC for Transportation",
  "Kalasam - QC for Fixing",
  "Dhwajasthambham Kavacham",
  "Dhwajasthambham Kavacham - QC for Making",
  "Dhwajasthambham Kavacham - QC for Transportation",
  "Dhwajasthambham Kavacham - QC for Fixing",
  "Client: Compound Wall"
];

export const BOTH_CONSTRUCTION_ITEMS = [
  "Client: Survey of the Temple Area and surroundings",
  "Temple Marking",
  "Senku sthapana - Where a stone is put beneath the main Garbhalaya ground.",
  "Client: Civil work - Foundation, plinth beam and columns",
  "Garbhalaya - 4 Steps by laying stones",
  "Mandapam Upapeetam",
  "Mandapam Pillars",
  "Client: Civil work Garbhalaya and Mandapam - Slab",
  "Sikaram Brick work",
  "Plastering and Finishing",
  "Salaharam Brick work",
  "Plastering and Finishing",
  "Cement Idols",
  "Dwajasthambham log purchase",
  "Client: Cement work - Dwajasthambham Peetam",
  "Dwajasthambham Brass Kavacham",
  "Door Frame - Making, Transportation, fixing",
  "Door Frame - QC for Making",
  "Door Frame - QC for Transportation",
  "Door Frame - QC for Fixing",
  "Door Shutters - Making, Transportation, Fixing, Polishing",
  "Door Shutters - QC for Making",
  "Door Shutters - QC for Transportation",
  "Door Shutters - QC for Fixing",
  "Door Shutters - QC for Polishing",
  "Dhwajatshambham - Making, Transportation, Fixing",
  "Dhwajatshambham - QC for Making",
  "Dhwajatshambham - QC for Transportation",
  "Dhwajatshambham - QC for Fixing",
  "Raja Gopuram - 4 Stages Upto Prastharam",
  "Client: Civil Work - Slab",
  "Sikaram - 4 stages",
  "Kalasam Designs",
  "Kalasam - QC for Making",
  "Kalasam - QC for Transportation",
  "Kalasam - QC for Fixing",
  "Dhwajasthambham Kavacham",
  "Dhwajasthambham Kavacham - QC for Making",
  "Dhwajasthambham Kavacham - QC for Transportation",
  "Dhwajasthambham Kavacham - QC for Fixing",
  "Client: Compound Wall"
];